/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaentra21;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
            System.out.println("Olá Mundo");
            //Comentários de linha
            /* Comentário de Bloco
            podemos fazer várias linhas
             */ 
            /**Comentarios de documentação tudo escrito aqui 
             * podemos transformar em um documento após gerar a
             * documentação
             */
            


    }
}
