/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package comandoleituragravacao;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        Scanner leitor = new Scanner(System.in);

        int idade = leitor.nextInt();

    }
}
